## 异常机制

Java是采用面向对象的方式来处理异常的。



### 一、异常类层次结构图

所有异常的根类为java.lang.Throwable。

Throwable下面又派生了两个子类：Error和Exception。

![图6-2 Java异常类层次结构图.png](.\image\389bf3773f8eccf2d33bee1cfaa75c69.png)![点击并拖拽以移动](data:image/gif;base64,R0lGODlhAQABAPABAP///wAAACH5BAEKAAAALAAAAAABAAEAAAICRAEAOw==)





### 二、Error类

Error是程序无法处理的错误，表示代码运行时 JVM(Java 虚拟机)出现的问题。

如当 JVM 所需的内存资源不足时，将出现 OutOfMemoryError。





### 三、Exception类

Exception是程序本身能够处理的异常，如：

- 空指针异常(NullPointerException)
- 数组下标越界异常(ArrayIndexOutOfBoundsException)
- 类型转换异常(ClassCastException)
- 算术异常(ArithmeticException)

**Exception类**分为：RuntimeException 运行时异常 与 CheckedException 已检查异常。



#### 3.1 RuntimeException类

RuntimeException异常，一般由编程错误导致的，经常需要通过增加“逻辑处理来避免这些异常”。

```java
//ArithmeticException异常逻辑处理
public class Test {
    public static void main(String[] args) {
        int b=0;
        if(b!=0){
            System.out.println(1/b);
        }
    }
}
```



```java
//NullPointerException异常逻辑处理
public class Test {
    public static void main(String[] args) {
        String str=null;
        if(str!=null){
            System.out.println(str.charAt(0));
        }
    }
}
```



```java
//ClassCastException异常逻辑处理
public class Test {
    public static void main(String[] args) {
        Animal a = new Dog();
        if (a instanceof Cat) {
            Cat c = (Cat) a;
        }
    }
}
```



```java
//ArrayIndexOutOfBoundsException异常逻辑处理
public class Test {
    public static void main(String[] args) {
        int[] arr = new int[5];
        int a = 5;
        if (a < arr.length) {
            System.out.println(arr[a]);
        }
    }
}
```



```java
//NumberFormatException异常逻辑处理
import java.util.regex.Matcher;
import java.util.regex.Pattern;
 
public class Test {
    public static void main(String[] args) {
        String str = "1234abcf";
        Pattern p = Pattern.compile("^\\d+$");
        Matcher m = p.matcher(str);
        if (m.matches()) { // 如果str匹配代表数字的正则表达式,才会转换
            System.out.println(Integer.parseInt(str));
        }
    }
}
```



#### 3.2 CheckedException类

所有不是RuntimeException的异常，统称为CheckedException，又被称为“已检查异常”，如IOException、SQLException等以及用户自定义的Exception异常。 





### 四、异常的处理方式

#### 4.1 try-catch-finally

![图6-10 异常处理.png](https://img-blog.csdnimg.cn/img_convert/de284582f66e89f17f8efff9cf4004b0.png)![点击并拖拽以移动](data:image/gif;base64,R0lGODlhAQABAPABAP///wAAACH5BAEKAAAALAAAAAABAAEAAAICRAEAOw==)





#### 4.2 声明异常(throws子句)

当CheckedException产生时，不一定立刻处理它，可以再把异常throws出去。

```java
public static void readFile(String fileName) throws FileNotFoundException,IOException {}
```

![点击并拖拽以移动](data:image/gif;base64,R0lGODlhAQABAPABAP///wAAACH5BAEKAAAALAAAAAABAAEAAAICRAEAOw==)