## 异常

- 程序在运行时，如果Python解释器遇到到一个错误，会停止程序的执行，并且提示一些错误信息，这就是异常。
- 程序停止执行并且提示错误信息这个动作，我们通常称之为：抛出(raise)异常。

![001_异常示意图](image/001_异常示意图.png)

### 1 捕获异常

```python
# 简单的捕获异常例子
try:
    num=int(input("请输入数字："))
except:
    print("请输入正确的数字")
```

```python
# 异常类型捕获例子
try:
    num=int(input("请输入整数: "))
    result=8/num
    print(result)
except ValueError:
    print("请输入正确的整数")
except ZeroDivisionError:
    print("除数不能为0")
```

```python
# 捕获未知错误例子
try:
    num=int(input("请输入整数: "))
    result=8/num
    print(result)
except ValueError:
    print("请输入正确的整数")
except ZeroDivisionError:
    print("除数不能为0")
except Exception as e:
    print(e)
else:
    print("正常执行")
finally:
    print("执行完成，但是不保证正确")
```



### 2 异常的传递

异常的传递——当函数/方法执行出现异常，会将异常传递给函数/方法的调用一方。

如果传递到主程序，仍然没有异常处理，程序才会被终止。

```python
# 异常的传递例子
def test1():
    return int(input("请输入一个整数: "))
def test2():
    return test1()
try:
    print(test2())
except ValueError:
    print("请输入正确的整数")
except Exception as e:
    print(e)
```



### 3 抛出raise异常

```python
# raise 异常例子
def input_passwd():
    pwd=input("请输入密码:")
    if len(pwd) >=8:
        return pwd
    ex=Exception("密码长度不够")
    raise ex

try:
    user_pwd=input_passwd()
    print(user_pwd)
except Exception as e:
    print(e)
```







